name: OIDC and NPM Push
on:
  push:
    branches: [ main ]

permissions:
  id-token: write      
  contents: read

jobs:
  push_npm:
    runs-on: ubuntu-latest
    name: OIDC Auth + debian package Push
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get OIDC token
        id: auth
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"github_action\"}" https://api.cloudsmith.io/openid/testcheck/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
                    
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Cloudsmith Push Debian Package
         - uses: actions/checkout@v4
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "raw"
          owner: "testcheck"
          repo: "github_action"
          file: "./npm.zip"
          name: "Raw Test"
          summary: "Github Action test of raw pushes"
          description: "See https://github.com/cloudsmith-io/action"
          version: ${{ github.sha}}

       
            
