name: OIDC and NPM Push
on:
  push:
    branches: [ main ]

permissions:
  id-token: write      
  contents: read

jobs:
  push_npm:
    runs-on: ubuntu-latest
    name: OIDC Auth + debian package Push
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get OIDC token
        id: auth
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"github_action\"}" https://api.cloudsmith.io/openid/testcheck/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
                    
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Cloudsmith Push Debian Package
        uses: cloudsmith-io/action@v0.6.14
        with:
          command: 'push'
          format: 'deb'
          owner: 'testcheck'             # Your Cloudsmith account name or org name (namespace)
          repo: 'github_action'         # Your Cloudsmith Repository name (slug)
          distro: 'debian'     # Your Distribution  (i.e Debian, Ubuntu)
          release: 'buster'         # Your Distribution Release (i.e xenial, buster)
          republish: 'true'          # needed if version is not changing
          file: './my-app-1.0.jar'  # debian package filename

       
            
