name: OIDC and NPM Push
on:
  push:
    branches: [ main ]

permissions:
  id-token: write      
  contents: read

jobs:
  oidc_auth:
    runs-on: ubuntu-latest
    name: OIDC Authentication
    outputs:
      cloudsmith_api_key: ${{ steps.auth.outputs.cloudsmith_api_key }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get OIDC token
        id: auth
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=cloudsmith" | jq -r '.value')

          token=$(curl -X POST -H "Content-Type: application/json" \
                 -d "{\"oidc_token\": \"$value\", \"service_slug\": \"github_action\"}" \
                 https://api.cloudsmith.io/openid/testcheck/ | jq -r '.token')

          echo "Received Token: $token"
          echo "cloudsmith_api_key=$token" >> $GITHUB_ENV
          echo "::set-output name=cloudsmith_api_key::$token"

  push_npm:
    runs-on: ubuntu-latest
    name: NPM Push Job
    needs: oidc_auth
    steps:
      - uses: actions/checkout@v4

      - name: Push Package to Cloudsmith
        uses: cloudsmith-io/action@v1
        with:
          api-key: ${{ needs.oidc_auth.outputs.cloudsmith_api_key }}
          command: "push"
          format: "npm"
          owner: "testcheck"
          repo: "github_action"
          republish: "false"
          file: "./npm-scripts-1.0.0.tgz"
