name: OIDC Setup
on:
  push:
    branches: [ main ]
permissions:
  id-token: write      
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: OIDC setup job 
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get OIDC token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"github_action\"}" https://api.cloudsmith.io/openid/testcheck/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
                    
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV