name: OIDC and NPM Push
on:
  push:
    branches: [ main ]

permissions:
  id-token: write      
  contents: read

jobs:
  push_npm:
    runs-on: ubuntu-latest
    name: OIDC Auth + NPM Push
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get OIDC token
        id: auth
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=cloudsmith" | jq -r '.value')

          token=$(curl -X POST -H "Content-Type: application/json" \
                 -d "{\"oidc_token\": \"$value\", \"service_slug\": \"github_action\"}" \
                 https://api.cloudsmith.io/openid/testcheck/ | jq -r '.token')

          echo "Received Token: $token"
          echo "cloudsmith_api_key=$token" >> $GITHUB_ENV

      ...
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.cloudsmith_api_key }}
          command: "push"
          format: "maven"
          owner: "testcheck"
          repo: "github_action"
          republish: "true"
          file: "./cloudsmith-maven-example-1.0.0.jar"
          executable: "false" # Add this to use pip instead
